# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export PS1="[\u@\h \W]\$ "
export EDITOR=vim
export GOPATH=/usr/local
export SANDBOX_BINARY=/usr/mysql

alias d="/usr/local/bin/docker_wrap.sh"
alias cpanm="sudo /usr/local/bin/cpanm"
alias perl="rlwrap perl -MData::Dumper -MDBI -M'Digest::MD5 qw{md5_hex}' -M'FindBin qw{\$Bin}'"
alias ls="ls --color"
alias ll="ls -l"
alias remote_ip="curl -s http://api.aoikujira.com/ip/json | jq -r .REMOTE_ADDR"

if [ -x /usr/local/bin/git_wrap.sh ] ; then
  alias g="/usr/local/bin/git_wrap.sh"
else
  alias g="git"
fi
alias use="git checkout"

if [ -f ~/.bashrc2 ] ; then
  . ~/.bashrc2
fi
